DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP SCHEMA IF EXISTS orders_db CASCADE;
DROP SCHEMA IF EXISTS order_test;
DROP SCHEMA IF EXISTS orders_schema;
DROP TABLE IF EXISTS events